### ISSUE TITLE
Get absences

### ISSUE THREAD

**Issue by SoldatXwing** [Suiram1701/WebUntisAPI.Client#4]
Hello, I was wondering if it is possible to get the absences within a school year via the API? I haven't found anything direct about this.

**Comment by Suiram1701** [comment]
WebUntis supports it and because of the fact that the GUI get everything from the API there also have to be endpoints to request these data. I created this API client by looking on the traffic tab and a bit reverse engeneering so what I can't see I can't implement that good. In [another WebUntis API client](https://github.com/SchoolUtils/WebUntis/blob/51576aaeda7af7ec47c818ab22a0e434b6fcb148/src/base.ts#L871) (written in ts) you can see that this endpoint exists.

**Comment by Suiram1701** [comment]
But I doesn't think that this is from use for you as long your not a teacher. In the json-rpc API of Untis I found also a method ot get the absences but I was not permitet to use it (as a student user).

**Comment by SoldatXwing** [comment]
Alright, that's all I wanted to know, whether this endpoint already exists in this API. Maybe I will expand this API to include this in the future. If you would like to talk more about this, feel free to add me on Discord: `soldatxwing`
